In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movies = movies.merge(credits,on='title') #merges the content on title

In [6]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [7]:
#what we are adding to project
#geners
#id
#keywords
#title
#overview
#cast
#crew

movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [8]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [10]:
movies.dropna(inplace=True) # drop the null data

In [11]:
movies.duplicated().sum() #checks the duplicate  data.

0

In [12]:
movies.iloc[0].genres # iloc() function enables us to select a particular cell of the dataset

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [13]:
# to convert this data in specific list. ['Action','Adventure','Fantasy','Sci-Fi']
# ast.literal_eval converts the string list to list.
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [14]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [15]:
movies['genres'] = movies['genres'].apply(convert)

In [16]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [17]:
movies['keywords'] = movies['keywords'].apply(convert)

In [18]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [19]:
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [20]:
  movies['cast'] = movies['cast'].apply(convert3)

In [21]:
def fetch_diractor(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [22]:
movies['crew'] = movies['crew'].apply(fetch_diractor)

In [23]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [24]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [25]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [26]:
#now we have to remove spaces because For. Ex Sam Worthington here Sam is other entity and Worthington is other so our system
#will not confuse with same name.

In [27]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [28]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [29]:
movies['tags'] =  movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [30]:
new_df = movies[['movie_id','title','overview','tags']]

In [31]:
new_df

,movie_id,title,overview,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction, c..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction, basedonnov..."
...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller, unitedstates–mexicob..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance, EdwardBurns, KerryBishé, Mar..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TVMovie, date, loveat..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,"[DanielHenney, ElizaCoupe, BillPaxton, DanielH..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[Documentary, obsession, camcorder, crush, dre..."

In [32]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\VAIBHA~1\AppData\Local\Temp/ipykernel_12592/3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [33]:
new_df.head()

,movie_id,title,overview,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy ScienceFiction cultur...
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action ocean drugabuse exoti...
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime spy basedonnovel secret...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller dccomics crimefigh...
4,49529,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure ScienceFiction basedonnovel m...

In [34]:
# here's point how do we say these 5 movies are similar?
# ----> so we need to find the similarity between two movies.
# ---->we will use text-vectorization.
# we will use bag-of-words

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [36]:
vectors = cv.fit_transform(new_df['tags'],'overview').toarray()

In [37]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [38]:
cv.get_feature_names()

['16thcentury',
 '17thcentury',
 '18thcentury',
 '1910s',
 '1930s',
 '1940s',
 '1950s',
 '1960s',
 '1970s',
 '1980s',
 '1990s',
 '19thcentury',
 '21stcentury',
 '3d',
 'aaroneckhart',
 'aarontaylor',
 'abbiecornish',
 'abhishekbachchan',
 'abigailbreslin',
 'aborigine',
 'abrams',
 'absurdism',
 'abuse',
 'abusivehusband',
 'accident',
 'action',
 'actionhero',
 'activist',
 'actor',
 'actress',
 'adambeach',
 'adambrody',
 'adamcarolla',
 'adamdriver',
 'adamgarcia',
 'adamgoldberg',
 'adammckay',
 'adamrifkin',
 'adamsandler',
 'adamscott',
 'adamshankman',
 'adaptation',
 'addiction',
 'adolescence',
 'adolfhitler',
 'adoptedchild',
 'adoption',
 'adoptivefather',
 'adrianlyne',
 'adrienbrody',
 'adriennebarbeau',
 'adultanimation',
 'adultery',
 'advancement',
 'adventure',
 'adversary',
 'advertisingexecutive',
 'advertisingexpert',
 'advice',
 'affair',
 'affection',
 'afghanistan',
 'africa',
 'africanamerican',
 'aftercreditsstinger',
 'afterlife',
 'agedifference',
 'agent',
 'aggressionbyanimal',
 'aging',
 'aidanquinn',
 'aids',
 'aimeegarcia',
 'airforce',
 'airplane',
 'airplanecrash',
 'airport',
 'akshaykumar',
 'alanalda',
 'alanarkin',
 'alanparker',
 'alanrickman',
 'alantudyk',
 'alaska',
 'albertbrooks',
 'albertfinney',
 'alberthughes',
 'alcatraz',
 'alcohol',
 'alcoholabuse',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alecguinness',
 'alejandroamenábar',
 'alejandrogonzáleziñárritu',
 'alessandronivola',
 'alexanderpayne',
 'alexanderskarsgård',
 'alexandradaddario',
 'alexandreaja',
 'alexapenavega',
 'alexisbledel',
 'alexkendrick',
 'alexpettyfer',
 'alexproyas',
 'alfonsocuarón',
 'alfredhitchcock',
 'alfredmolina',
 'alfrewoodard',
 'alicebraga',
 'aliceeve',
 'aliciasilverstone',
 'aliciavikander',
 'aliciawitt',
 'alien',
 'alienabduction',
 'alienation',
 'alienattack',
 'aliencontact',
 'alieninfection',
 'alieninvasion',
 'alienlife',
 'alienphenomenons',
 'alienplanet',
 'alilarter',
 'alisonlohman',
 'alligator',
 'alpacino',
 'alps',
 'alterego',
 'alternatedimension',
 'alternatehistory',
 'alternatereality',
 'alternativereality',
 'alysonhannigan',
 'alzheimer',
 'amandabynes',
 'amandapeet',
 'amandaseyfried',
 'amazon',
 'ambassador',
 'amberheard',
 'ambertamblyn',
 'ambition',
 'ambulance',
 'ambush',
 'americaferrera',
 'american',
 'americanabroad',
 'americancivilwar',
 'americandream',
 'americanflag',
 'americanfootball',
 'americanfootballplayer',
 'amnesia',
 'amsterdam',
 'amusementpark',
 'amyadams',
 'amyheckerling',
 'amypoehler',
 'amyryan',
 'amysmart',
 'anaclaudiatalancón',
 'anandtucker',
 'anarchiccomedy',
 'ancientchina',
 'ancientegypt',
 'ancientgreece',
 'ancientrome',
 'ancientworld',
 'anderson',
 'andiemacdowell',
 'andrebraugher',
 'andrewadamson',
 'andrewbujalski',
 'andrewdavis',
 'andrewfleming',
 'andrewgarfield',
 'andrewniccol',
 'andrewstanton',
 'android',
 'andrzejbartkowiak',
 'andyfickman',
 'andygarcía',
 'andylau',
 'andysamberg',
 'andyserkis',
 'andytennant',
 'angel',
 'angelabassett',
 'angelinajolie',
 'anger',
 'anglee',
 'animal',
 'animalattack',
 'animalhorror',
 'animallead',
 'animalprotection',
 'animalsidekick',
 'animation',
 'anime',
 'anjelicahuston',
 'annabellasciorra',
 'annafaris',
 'annafriel',
 'annakendrick',
 'annapaquin',
 'annasophiarobb',
 'annearcher',
 'annebancroft',
 'annefletcher',
 'annehathaway',
 'anneheche',
 'annemoss',
 'annettebening',
 'anonymity',
 'anonymousletter',
 'anotherdimension',
 'ant',
 'antarctic',
 'antarctica',
 'anthology',
 'anthonyanderson',
 'anthonyhopkins',
 'anthonymackie',
 'anthonyminghella',
 'anthonyquinn',
 'anthonyrusso',
 'anthropomorphism',
 'anti',
 'antihero',
 'antisemitism',
 'antiterror',
 'antoinefuqua',
 'antoncorbijn',
 'antoniobanderas',
 'antonyelchin',
 'apartheid',
 'apartment',
 'ape',
 'apocalypse',
 'apocalyptic',
 'apostle',
 'apprentice',
 'aquarium',
 'arab',
 'arbitrarylaw',
 'archaeologist',
 'archeology',
 'archer',
 'archery',
 'architect',
 'arctic',
 'arcy',
 'area51',
 'arena',
 'argument',
 'aristocrat',
 'arizona',
 'armandassante',
 'armiehammer',
 'arminmueller',
 'armoredcar',
 'armsdeal',
 'armsdealer',
 'army',
 'arnoldschwarzenegger',
 'arrangedmarriage',
 'arrest',
 'arrogance',
 'arson',
 'art',
 'artgallery',
 'arthouse',
 'artifact',
 'artificialinsemination',
 'artificialintelligence',
 'artist',
 'arttheft',
 'artthief',
 'asabutterfield',
 'ashleyjudd',
 'ashleytisdale',
 'ashtonkutcher',
 'asia',
 'aspiringsinger',
 'assassin',
 'assassination',
 'assassinationattempt',
 'assault',
 'assaultrifle',
 'assignment',
 'assistant',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlete',
 'atlanticocean',
 'atomegoyan',
 'atomicbomb',
 'attack',
 'attemptedmurder',
 'attemptedrape',
 'attempttoescape',
 'attic',
 'auction',
 'audiotape',
 'audition',
 'audreyhepburn',
 'audreytautou',
 'aunt',
 'auntniecerelationship',
 'australia',
 'australianoutback',
 'austria',
 'author',
 'autism',
 'auto',
 'automobileracing',
 'autoritianeducation',
 'awkwardness',
 'ax',
 'baby',
 'babysitter',
 'bachelor',
 'backpacker',
 'badboss',
 'badluck',
 'badmother',
 'bagoverhead',
 'bahamas',
 'ball',
 'ballet',
 'balloon',
 'baltasarkormákur',
 'baltimoremaryland',
 'bammargera',
 'band',
 'bangkok',
 'bank',
 'banker',
 'banking',
 'bankrobber',
 'bankrobbery',
 'bar',
 'barbarahershey',
 'barbarian',
 'barbrastreisand',
 'barcelonaspain',
 'barfight',
 'barn',
 'barrylevinson',
 'barrypepper',
 'barrysonnenfeld',
 'barsandrestaurants',
 'baseball',
 'baseballbat',
 'basedonarticle',
 'basedoncartoon',
 'basedonchildren',
 'basedoncomicbook',
 'basedoncomicstrip',
 'basedonfairytale',
 'basedonfilm',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonshortstory',
 'basedonstagemusical',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'bat',
 'bathroomhumor',
 'bathtub',
 'batman',
 'battle',
 'battleassignment',
 'battlefield',
 'battleforpower',
 'bazluhrmann',
 'bdsm',
 'beach',
 'beachhouse',
 'bear',
 'beard',
 'beast',
 'beating',
 'beautifulwoman',
 'beauty',
 'beautycontest',
 'becominganadult',
 'bedroom',
 'beer',
 'beguilement',
 'beheading',
 'belgium',
 'benaffleck',
 'benbarnes',
 'benchaplin',
 'benedictcumberbatch',
 'benfoster',
 'bengazzara',
 'beniciodeltoro',
 'benitomussolini',
 'benjaminbratt',
 'benkingsley',
 'bennofürmann',
 'benstiller',
 'benwhishaw',
 'berlin',
 'berniemac',
 'bestfriend',
 'bestfriendsinlove',
 'bet',
 'betrayal',
 'bettemidler',
 'bettythomas',
 'beverlyhills',
 'beyoncéknowles',
 'bias',
 'bible',
 'bigfamily',
 'biker',
 'bikini',
 'billard',
 'billbellamy',
 'billcondon',
 'billewoodruff',
 'billhader',
 'billionaire',
 'billmoseley',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billyburke',
 'billyconnolly',
 'billycrudup',
 'billycrystal',
 'billythekid',
 'billywilder',
 'billyzane',
 'binoculars',
 'biography',
 'biologicalweapon',
 'biology',
 'bird',
 'birth',
 'birthday',
 'bisexual',
 'bisexuality',
 'bite',
 'bittersweet',
 'blackandwhite',
 'blackhole',
 'blackhumor',
 'blackmagic',
 'blackmail',
 'blackmen',
 'blackout',
 'blackpeople',
 'blacksmith',
 'blade',
 'blakelively',
 'blast',
 'blaxploitation',
 'blind',
 'blinddate',
 'blindness',
 'blindnessandimpairedvision',
 'blizzard',
 'blog',
 'blonde',
 'blood',
 'bloodsplatter',
 'blowjob',
 'blues',
 'boardingschool',
 'boat',
 'boatchase',
 'boazyakin',
 'bobbyfarrelly',
 'bobclark',
 'bobgunton',
 'bobhoskins',
 'bobodenkirk',
 'body',
 'bodyexchange',
 'bodyguard',
 'bodyhorror',
 'bokeemwoodbine',
 'bollywood',
 'bomb',
 'bomber',
 'bombing',
 'bondage',
 'bongjoon',
 'bonniehunt',
 'boobytrap',
 'book',
 'bookstore',
 'boredom',
 'boss',
 'boston',
 'botanist',
 'bounty',
 'bountyhunter',
 'bourgeoisie',
 'bowandarrow',
 'bowling',
 'boxer',
 'boxing',
 'boxingmatch',
 'boy',
 'boyfriend',
 'boyfriendex',
 'boyfriendgirlfriendrelationship',
 'boygenius',
 'boys',
 'bradanderson',
 'bradbird',
 'braddourif',
 'bradfurman',
 'bradleycooper',
 'bradpeyton',
 'bradpitt',
 'bradsilberling',
 'bradycorbet',
 'brain',
 'braintumor',
 'brainwashing',
 'brandont',
 'bravery',
 'brawl',
 'brazil',
 'brazilian',
 'break',
 'breakdance',
 'breakingthefourthwall',
 'breast',
 'breckeisner',
 'breckinmeyer',
 'brendanfraser',
 'brendangleeson',
 'brentonthwaites',
 'brentspiner',
 'brettratner',
 'briancox',
 'briandennehy',
 'briandepalma',
 'brianhelgeland',
 'brianlevant',
 'brianrobbins',
 'briantaylor',
 'briantrenchard',
 'bride',
 'bridegroom',
 'bridesmaid',
 'bridge',
 'bridgetfonda',
 'brielarson',
 'brien',
 'britain',
 'british',
 'britisharmy',
 'britishempire',
 'britishsecretservice',
 'britmarling',
 'brittanymurphy',
 'brittanysnow',
 'brittrobertson',
 'broadway',
 'brokenengagement',
 'brokenneck',
 'broker',
 'bronx',
 'brookeshields',
 'brooklynnewyorkcity',
 'brooks',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothersisterrelationship',
 'bruceberesford',
 'brucecampbell',
 'brucedern',
 'brucegreenwood',
 'brucewillis',
 'brutality',
 'bryancranston',
 'bryansinger',
 'brycedallashoward',
 'budapest',
 'buddhism',
 'buddhistmonk',
 'buddycomedy',
 'buddycop',
 'bulletwound',
 'bully',
 'bullying',
 'bunker',
 'bunny',
 'bureaucracy',
 'burglar',
 'buriedalive',
 'burnedalive',
 'burrsteers',
 'burtlancaster',
 'burtreynolds',
 'bus',
 'bush',
 'business',
 'businessman',
 'businessstart',
 'busride',
 'butler',
 'bythewood',
 'cabin',
 'cabininthewoods',
 'cage',
 'cairo',
 'california',
 'callgirl',
 'cambodia',
 'camcorder',
 'cameronbright',
 'cameroncrowe',
 'camerondiaz',
 'camgigandet',
 'camillabelle',
 'camp',
 'campaign',
 'campbellscott',
 'camping',
 'campus',
 'canada',
 'cancer',
 'candlelightvigil',
 'candy',
 'cannabis',
 'cannibal',
 'cannibalism',
 'canoe',
 'canuxploitation',
 'caper',
 'capitalism',
 'captain',
 'captive',
 'capture',
 'car',
 'caraccident',
 'carbomb',
 'carchase',
 'carcrash',
 'cardealer',
 'cardgame',
 'career',
 'careerwoman',
 'caretaker',
 'carexplosion',
 'careymulligan',
 'cargoship',
 'caribbean',
 'caricevanhouten',
 'carjourney',
 'carlagugino',
 'carlfranklin',
 'carlossaldanha',
 'carlyschroeder',
 'carmenejogo',
 'carnival',
 'carpet',
 'carrace',
 'carrie',
 'carriefisher',
 'carsetonfire',
 'cartoon',
 'caruso',
 'caryelwes',
 'caseyaffleck',
 'casino',
 'castle',
 'castration',
 'cat',
 'cataclysm',
 'catandmouse',
 'catastrophe',
 'cateblanchett',
 'catherinedeneuve',
 'catherinehardwicke',
 'catherinekeener',
 'catherinemccormack',
 'catherineo',
 'catherinezeta',
 'catholic',
 'catholicchurch',
 'catholicism',
 'catholicpriest',
 'cattledrive',
 'cavalry',
 'cave',
 'cavemen',
 'cedrictheentertainer',
 'celebration',
 'celebrity',
 'cello',
 'cellphone',
 'cemetery',
 'centralandsouthamerica',
 'centralpark',
 'ceremony',
 'cgi',
 'chadmichaelmurray',
 'chainsaw',
 'championship',
 'chance',
 'chandor',
 'change',
 'changingthepastorfuture',
 'channingtatum',
 'chaos',
 'charity',
 'charlesdance',
 'charlesferguson',
 'charlesherman',
 'charlesmartinsmith',
 'charless',
 'charliecox',
 'charlieday',
 'charliehunnam',
 'charliesheen',
 'charlietahan',
 'charlizetheron',
 'charlotterampling',
 'charltonheston',
 'chase',
 'chasesandraces',
 'chauffeur',
 'chazzpalminteri',
 'cheating',
 'cheatingwife',
 'cheerleader',
 'chef',
 'chemical',
 'cher',
 'chevychase',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabuse',
 'childhero',
 'childhoodfriends',
 'childhoodmemory',
 'childhoodtrauma',
 'childlabour',
 'childmurderer',
 'childprodigy',
 'children',
 'chimcbride',
 'chimp',
 'chimpanzee',
 'china',
 'chinatown',
 'chipmunk',
 'chiwetelejiofor',
 'chloëgracemoretz',
 'chloësevigny',
 'chocolate',
 'choimin',
 'choir',
 'cholo',
 'chosenone',
 'chowyun',
 'chriscolumbus',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chriskattan',
 'chrisklein',
 'chrismiller',
 'chrisnoth',
 'chriso',
 'chrispine',
 'chrispratt',
 'chrisrock',
 'chrissanders',
 'christ',
 'christian',
 'christianbale',
 'christianclavier',
 'christianfilm',
 'christianity',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christmas',
 'christmascarol',
 'christmaseve',
 'christmasparty',
 'christmastree',
 'christophereccleston',
 'christopherguest',
 'christopherlambert',
 'christopherlloyd',
 'christophermcdonald',
 'christophermcquarrie',
 'christophermintz',
 'christophernolan',
 'christopherplummer',
 'christopherreeve',
 'christopherwalken',
 'christophwaltz',
 'christucker',
 'chriswedge',
 'chrisweitz',
 'chu',
 'chuckrussell',
 'church',
 'churchchoir',
 'churchservice',
 'cia',
 'ciaagent',
 'ciaránhinds',
 'cigarettesmoking',
 'cigarsmoking',
 'cillianmurphy',
 'cinderella',
 'cinema',
 'circus',
 'city',
 'cityruin',
 'civilrights',
 'civilwar',
 'clairedanes',
 'claireforlani',
 'clancybrown',
 'clarkgable',
 'class',
 'classdifferences',
 'classicalmusic',
 'classprejudice',
 'classroom',
 'classsociety',
 'claudevandamme',
 'claustrophobia',
 'cleaduvall',
 'clerk',
 'cliffcurtis',
 'climate',
 'climatechange',
 'climbing',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clocktower',
 'clone',
 'cloning',
 'clown',
 'clowning',
 'clumsyfellow',
 'coach',
 'coalmining',
 'coastguard',
 'cocaine',
 'cockneyaccent',
 'cockroach',
 'code',
 'coffin',
 'cohabitant',
 'cohen',
 'coldwar',
 'colehauser',
 'colinfarrell',
 'colinfirth',
 'collector',
 'college',
 'collegestudent',
 'colmfeore',
 'colmmeaney',
 'colombia',
 'colonel',
 'colonialism',
 'colony',
 'colorado',
 'coma',
 'combat',
 'comeback',
 'comedian',
 'comedy',
 'comet',
 'comicbook',
 'comingofage',
 'comingout',
 'commando',
 'commercial',
 'commune',
 'communism',
 'community',
 'company',
 'compass',
 'competition',
 'composer',
 'compulsivegambling',
 'computer',
 'computerhacker',
 'computerprogram',
 'computervirus',
 'conartist',
 'concentrationcamp',
 'concert',
 'conciliation',
 'condom',
 'confederatesoldier',
 'confession',
 'confidence',
 'congress',
 'conman',
 'connell',
 'connienielsen',
 'connor',
 'conradvernon',
 'conspiracy',
 'conspiracyofmurder',
 'conspiracytheory',
 'contest',
 'contractkiller',
 'control',
 'conveniencestore',
 'convertible',
 'convict',
 'convoy',
 'cook',
 'cooking',
 'cop',
 'cops',
 'corbinbernsen',
 'coreyfeldman',
 'coronation',
 'corporation',
 'corpse',
 'corruptcop',
 'corruption',
 'cosmatos',
 'costasmandylor',
 'costume',
 'countdown',
 'countryhouse',
 'countrylife',
 'countrymusic',
 'countryside',
 'coupd',
 'courage',
 'court',
 'courtcase',
 'courteneycox',
 'courthouse',
 'courtroom',
 'cover',
 'coveredinvestigation',
 'cow',
 'cowardice',
 'cowardliness',
 'cowboy',
 'crab',
 'craigbierko',
 'craiggillespie',
 'craigt',
 'crash',
 'creature',
 'crime',
 'crimefamily',
 'crimefighter',
 'criminal',
 'criminalmastermind',
 'crisis',
 'crispinglover',
 'crocodile',
 'crookedlawyer',
 'cross',
 'crossdressing',
 'crucifix',
 'crucifixion',
 'cruelty',
 'cruise',
 'crusade',
 'crush',
 'crying',
 'cryogenics',
 'cuba',
 'cubagoodingjr',
 ...]

In [39]:
# we will use "cosine distance" between movie vectors insted of "euclidian distance".

In [40]:
from sklearn.metrics.pairwise import cosine_similarity

In [41]:
similarity = cosine_similarity(vectors)

In [42]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(47, 0.3849001794597506),
 (2378, 0.34426518632954817),
 (61, 0.3333333333333334),
 (83, 0.3142696805273545),
 (2409, 0.30123203803835463)]

In [43]:
def recommend(movie):
    movie_index = new_df[new_df['title']== movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)
    return

In [44]:
recommend('The Dark Knight Rises')

The Dark Knight
Batman Begins
Harsh Times
Shinjuku Incident
Raise the Titanic

In [45]:
import pickle

In [46]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [47]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [49]:
pickle.dump(new_df.to_dict(),open('movies_dict.pkl','wb'))

In [50]:
pickle.dump(similarity,open('similarity.pkl','wb'))